### ISSUE TITLE
Tilde should be written in LaTeX

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [shcaba/Sebastes_melanops_WA#14]
https://github.com/shcaba/Sebastes_melanops_WA/blob/21fd91c1da82e4afd47fe9fe0b10272c8f1165b9/Document/01c_acronyms.Rmd#L15

Should be
```
ENSO - El Ni\~{n}o Southern Oscillation
```

**Comment by shcaba** [comment]
Thanks you for that correction.
