### ISSUE TITLE
How do we want to decide NSamp for biodata?  I may need to re-pull sport data to get actual sample dates if we want to do each sample day individually.  Let's discuss! 

### ISSUE THREAD

**Issue by KSten** [shcaba/Sebastes_melanops_WA#4]

**Comment by tsoutt** [comment]
We can't do at trip level. The best Kristen can do is by date of catch for post 2017. I think we used to do was either the number of sequence numbers/sample numbers or count of fish by year.

**Comment by KSten** [comment]
biodata has been re-pulled with the fish sample date as well.  I think we can go with a count of "fish_sample_date"'s by year unless you wanted to go to the individual fish level.

Data are here: https://docs.google.com/spreadsheets/d/1GVlBF636vUqOO5-gPFfm8PvA77MXkFnl/edit?usp=share_link&ouid=100258823246786665986&rtpof=true&sd=true

**Comment by KSten** [comment]
@shcaba and I emailed and decided best course of action is count of fish sample date.  I made a table here for ease: https://docs.google.com/spreadsheets/d/1nZh3qNuPY4VbD-SSBpyf29SjmGZtQEJU/edit?usp=share_link&ouid=100258823246786665986&rtpof=true&sd=true
