### ISSUE TITLE
50 Lengths for Check of Alive, Dead and sitting, Filletted Lengths

### ISSUE THREAD

**Issue by KSten** [shcaba/Sebastes_melanops_WA#6]
I added to the google drive a short description and figure for the 50 Black Rockfish chosen randomly to get the length differences while on survey this fall.  It can be found here: https://docs.google.com/document/d/1UCJ32E8ua0G2Wp1j6hiR6pPS6FN7uddN/edit?usp=share_link&ouid=100258823246786665986&rtpof=true&sd=true  AND I've attached it to this issue as well if it's easier to pull from here?  I'm not sure what is easiest for everyone.  Is there a better way to let people know for things like this?  Would you prefer an email?

[BlackRockfish50FishLengthChecks.docx](https://github.com/shcaba/Sebastes_melanops_WA/files/10484631/BlackRockfish50FishLengthChecks.docx)

**Comment by shcaba** [comment]
Do you mind adding some context at the top of this document regarding this comparison? This will help frame results.

**Comment by KSten** [comment]
of course, no problem!  I'll try and get it added by the end of today.

**Comment by KSten** [comment]
@shcaba I added a short description on the google doc.  I'm not sure I'm savvy enough to figure out how to add it to the Github pre-assessment site, but as long as it's enough context for you, I think it's ready to go.
