### ISSUE TITLE
L/W biodata cleaning up

### ISSUE THREAD

**Issue by shcaba** [shcaba/Sebastes_melanops_WA#7]
Kristen- you mentioned this needed to be done, so I am just noting it here as an open issue and assigning you.

**Comment by KSten** [comment]
![image](https://user-images.githubusercontent.com/45439711/217961178-e7ac2c6a-4f5c-444a-94c2-906406a7ac9e.png)

Still working at this.  I have 22 lengths that are suspect with no associated weights, 8 are pretty aggregious, 1 in particular.  Deciding what to do with these fish.

**Comment by shcaba** [comment]
Could you drop in a length-weight plot here including all samples so we can look and see how much those 22 lengths are outliers?
